"use strict";
const $ = id => document.getElementById(id);
const statuses = ['Aktiv','Wartend','Nicht mehr verfolgt'];
const key = 'ideenwerk-v1';
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const euro = n => new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);
const dec = n => new Intl.NumberFormat('de-DE',{maximumFractionDigits:2}).format(n);
const uid = () => crypto.randomUUID();
const today = () => new Date().toLocaleDateString('sv-SE');
let ideas = [], mode = '', selected = '', blocked = false;
const amount = v => {const n=Number(v ?? 0);if(!Number.isFinite(n)||n<0||n>1e12)throw Error('Beträge und Stunden müssen zwischen 0 und 1 Billion liegen.');return Math.round(n*100)/100;};
function normalize(list){
 if(!Array.isArray(list))throw Error('Keine gültige Ideenliste.');
 const ids=new Set();return list.map(i=>{
 if(!i||typeof i.name!=='string'||!i.name.trim())throw Error('Eine Idee benötigt einen Namen.');
 const id=String(i.id||uid());if(ids.has(id))throw Error('Doppelte Ideen-ID.');ids.add(id);
 let resources=i.resources;if(resources===undefined){resources=[];if(i.invested||i.moneyInvested||i.timeHours)resources.push({name:'Bisheriger Ressourceneinsatz',type:'Sonstiges',cost:i.invested??i.moneyInvested??0,hours:i.timeHours??0,date:today()});}
 if(!Array.isArray(resources))throw Error('Ungültige Ressourcenliste.');
 return {id,name:i.name.trim(),category:String(i.category||'Sonstiges'),status:statuses.includes(i.status)?i.status:({'Beendet':'Nicht mehr verfolgt','In Arbeit':'Aktiv'}[i.status]||'Wartend'),revenue:amount(i.revenue??i.moneyEarned),tax:amount(i.tax),notes:String(i.notes||''),resources:resources.map(r=>{if(!r||!r.name||!/^\d{4}-\d{2}-\d{2}$/.test(r.date))throw Error('Ressourcen benötigen Name und Datum.');return {id:uid(),name:String(r.name),type:String(r.type||'Sonstiges'),date:r.date,cost:amount(r.cost),hours:amount(r.hours)};})};
 });
}
try{const raw=localStorage.getItem(key)??localStorage.getItem('business-ideas');if(raw)ideas=normalize(JSON.parse(raw));}catch(e){blocked=true;$('message').textContent='Gespeicherte Daten konnten nicht geladen werden. Sie werden nicht überschrieben. Bitte eine gültige Sicherung importieren. '+e.message;}
function persist(next){try{if(blocked)throw Error('Bitte zunächst eine gültige Sicherung importieren.');localStorage.setItem(key,JSON.stringify(next));ideas=next;render();$('message').textContent='';return true;}catch(e){$('message').textContent='Speichern fehlgeschlagen: '+e.message;return false;}}
function totals(i){const cost=i.resources.reduce((s,r)=>s+Math.round(r.cost*100),0)/100;return {cost,hours:i.resources.reduce((s,r)=>s+r.hours,0),net:Math.round((i.revenue-cost-i.tax)*100)/100};}
function filtered(){const q=$('search').value.toLowerCase();return ideas.filter(i=>(!$('status').value||i.status===$('status').value)&&(!$('category').value||i.category===$('category').value)&&`${i.name} ${i.notes}`.toLowerCase().includes(q));}
function render(){
 const old=$('category').value;$('category').innerHTML='<option value="">Alle Kategorien</option>'+[...new Set(ideas.map(i=>i.category))].sort().map(c=>`<option>${esc(c)}</option>`).join('');$('category').value=[...$('category').options].some(o=>o.value===old)?old:'';
 const list=filtered(), sum=list.reduce((a,i)=>{const t=totals(i);return {revenue:a.revenue+i.revenue,cost:a.cost+t.cost,net:a.net+t.net,hours:a.hours+t.hours};},{revenue:0,cost:0,net:0,hours:0});
 $('summary').innerHTML=[['Umsatz gesamt',euro(sum.revenue),`${list.length} Ideen in deiner Auswahl`],['Ressourcenkosten',euro(sum.cost),'Alle erfassten Ausgaben'],['Zeit investiert',dec(sum.hours)+' h','Dein bisheriger Einsatz'],['Nettogewinn',euro(sum.net),'Nach erfassten Kosten und Steuern']].map(([l,v,s])=>`<article class="stat"><small>${l}</small><strong>${v}</strong><p>${s}</p></article>`).join('');
 $('ideas').innerHTML=list.length?list.map(i=>{const t=totals(i);return `<article class="idea"><div><h3>${esc(i.name)}</h3><span class="badge ${i.status==='Aktiv'?'active':i.status==='Wartend'?'waiting':''}">${esc(i.status)}</span><span class="badge">${esc(i.category)}</span><p class="notes">${esc(i.notes)}</p></div><div><div class="metrics"><div><small>Umsatz</small><b>${euro(i.revenue)}</b></div><div><small>Kosten · ${dec(t.hours)} h</small><b>${euro(t.cost)}</b></div><div><small>Nettogewinn</small><b class="${t.net<0?'negative':''}">${euro(t.net)}</b></div></div><div class="actions"><button data-action="resource" data-id="${esc(i.id)}">+ Ressource</button><button data-action="edit" data-id="${esc(i.id)}">Bearbeiten</button><button data-action="delete" data-id="${esc(i.id)}">Löschen</button></div></div></article>`;}).join(''):'<div class="empty"><strong>Platz für deine nächste große Idee.</strong>Lege eine Idee an oder passe deine Filter an.</div>';
 $('resources').innerHTML=list.flatMap(i=>i.resources.map(r=>({i,r}))).sort((a,b)=>b.r.date.localeCompare(a.r.date)).map(({i,r})=>`<tr><td>${esc(r.date.split('-').reverse().join('.'))}<small>${esc(i.name)}</small></td><td>${esc(r.name)}</td><td>${esc(r.type)}</td><td>${dec(r.hours)} h</td><td>${euro(r.cost)}</td><td><button data-action="removeResource" data-id="${esc(i.id)}" data-resource="${esc(r.id)}" aria-label="Ressource löschen">×</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Noch keine Ressourcen in dieser Auswahl erfasst.</td></tr>';
 $('csv').disabled=!list.length;$('resourcesCsv').disabled=!list.some(i=>i.resources.length);
}
const input=(label,name,value='',type='text')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" max="1000000000000" step="0.01"':''} ${['name','date'].includes(name)?'required':''}></label>`;
const select=(label,name,options,value)=>`<label>${label}<select name="${name}">${options.map(o=>`<option ${o===value?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`;
function open(kind,id='',draft={}){mode=kind;selected=id;const i=ideas.find(i=>i.id===id)||draft;$('form').querySelector('[type=submit]').hidden=false;
 if(kind==='idea'){$('dialogTitle').textContent=id?'Idee bearbeiten':'Neue Idee';$('fields').innerHTML=input('Name der Idee','name',i.name)+`<div class="grid">`+input('Kategorie','category',i.category)+select('Status','status',statuses,i.status||'Wartend')+input('Bisheriger Umsatz (€)','revenue',i.revenue||0,'number')+input('Bisherige Steuern (€)','tax',i.tax||0,'number')+`</div><label>Beschreibung / nächste Schritte<textarea name="notes">${esc(i.notes)}</textarea></label><p>Ausgaben und Arbeitsstunden erfasst du anschließend über „+ Ressource“.</p>`;}
 if(kind==='resource'){$('dialogTitle').textContent='Ressource für '+i.name;$('fields').innerHTML=input('Ressource / Beschreibung','name')+`<div class="grid">`+select('Art','type',['Software','Material','Externe Leistung','Arbeitszeit','Marketing','Sonstiges'])+input('Datum','date',today(),'date')+input('Kosten (€)','cost',0,'number')+input('Zeit (Stunden)','hours',0,'number')+'</div><p>Bei Arbeitszeit nur tatsächlich angefallene Kosten eintragen.</p>';}
 if(kind==='generate'){$('dialogTitle').textContent='Ideen entwickeln';$('fields').innerHTML='<p>Vorlagenbasierte Vorschläge, angepasst an dein Thema. Ohne externe KI.</p>'+input('Dein Thema oder deine Fähigkeiten','topic','Webdesign')+select('Geschäftsmodell','model',['Dienstleistung','Digitales Produkt','Lokales Angebot'])+'<button type="button" id="suggest">Vorschläge erstellen</button><div id="suggestions"></div>';$('form').querySelector('[type=submit]').hidden=true;}
 $('modal').showModal();}
function close(){$('modal').close();}
function saveForm(event){event.preventDefault();const d=Object.fromEntries(new FormData($('form')));try{let next;if(mode==='idea'){if(!d.name.trim())throw Error('Bitte einen Namen eingeben.');const previous=ideas.find(i=>i.id===selected);const i={id:selected||uid(),name:d.name.trim(),category:d.category.trim()||'Sonstiges',status:d.status,revenue:amount(d.revenue),tax:amount(d.tax),notes:d.notes,resources:previous?.resources||[]};next=previous?ideas.map(x=>x.id===selected?i:x):[...ideas,i];}else if(mode==='resource'){if(!d.name.trim())throw Error('Bitte eine Ressource benennen.');next=ideas.map(i=>i.id===selected?{...i,resources:[...i.resources,{...d,id:uid(),name:d.name.trim(),cost:amount(d.cost),hours:amount(d.hours)}]}:i);}if(next&&persist(next))close();}catch(e){alert(e.message);}}
function csvCell(v){let s=String(v??'');if(typeof v==='string'&&/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csv(kind){const numeric=n=>n.toFixed(2).replace('.',',');let rows;if(kind==='ideas')rows=[['Name','Kategorie','Status','Zeit (h)','Ressourcenkosten (EUR)','Umsatz (EUR)','Steuern (EUR)','Nettogewinn (EUR)','Notiz'],...filtered().map(i=>{const t=totals(i);return [i.name,i.category,i.status,numeric(t.hours),numeric(t.cost),numeric(i.revenue),numeric(i.tax),numeric(t.net),i.notes];})];else rows=[['Idee','Datum','Ressource','Art','Zeit (h)','Kosten (EUR)'],...filtered().flatMap(i=>i.resources.map(r=>[i.name,r.date,r.name,r.type,numeric(r.hours),numeric(r.cost)]))];download(`${kind==='ideas'?'ideen':'ressourcen'}-${today()}.csv`,'\uFEFF'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n'),'text/csv;charset=utf-8');}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const id=b.dataset.id,i=ideas.find(i=>i.id===id);if(!i)return;if(b.dataset.action==='edit')open('idea',id);if(b.dataset.action==='resource')open('resource',id);if(b.dataset.action==='delete'&&confirm(`„${i.name}“ samt Ressourcen löschen?`))persist(ideas.filter(x=>x.id!==id));if(b.dataset.action==='removeResource'&&confirm('Diese Ressourcenbuchung löschen?'))persist(ideas.map(x=>x.id===id?{...x,resources:x.resources.filter(r=>r.id!==b.dataset.resource)}:x));});
let suggestions=[];
$('fields').addEventListener('click',e=>{if(e.target.id==='suggest'){const f=new FormData($('form')),topic=String(f.get('topic')).trim()||'dein Fachgebiet',model=f.get('model');const templates=model==='Dienstleistung'?[['Starter-Service','Biete ein klar begrenztes Einstiegspaket an.'],['Monatliche Betreuung','Entwickle eine wiederkehrende Betreuung für kleine Unternehmen.'],['Praxis-Workshop','Vermittle deine Fähigkeiten in einem bezahlten Workshop.']]:model==='Digitales Produkt'?[['Vorlagenpaket','Erstelle wiederverwendbare Vorlagen für ein häufiges Problem.'],['Mini-Kurs','Entwickle einen kompakten Kurs mit konkretem Ergebnis.'],['Nischen-Newsletter','Teste einen kostenpflichtigen Informationsdienst.']]:[['Lokaler Service','Teste dein Angebot mit drei Betrieben vor Ort.'],['Gruppenworkshop','Organisiere einen praktischen Workshop in deiner Region.'],['Beratung vor Ort','Biete eine Bestandsaufnahme mit konkreten Empfehlungen an.']];suggestions=templates.map(([name,notes])=>({name:topic+' · '+name,category:String(model),notes:notes+'\nNächster Schritt: Mit fünf potenziellen Kunden Bedarf und Zahlungsbereitschaft prüfen.'}));$('suggestions').innerHTML=suggestions.map((s,n)=>`<article class="suggestion"><h3>${esc(s.name)}</h3><p>${esc(s.notes)}</p><button type="button" data-pick="${n}">Idee übernehmen</button></article>`).join('');}if(e.target.dataset.pick!==undefined){const draft=suggestions[Number(e.target.dataset.pick)];close();open('idea','',draft);}});
$('new').onclick=()=>open('idea');$('generate').onclick=()=>open('generate');$('close').onclick=close;$('cancel').onclick=close;$('form').onsubmit=saveForm;['search','status','category'].forEach(id=>$(id).addEventListener('input',render));$('csv').onclick=()=>csv('ideas');$('resourcesCsv').onclick=()=>csv('resources');$('backup').onclick=()=>download('ideenwerk-sicherung-'+today()+'.json',JSON.stringify(ideas,null,2),'application/json');$('restore').onclick=()=>$('import').click();
$('import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const next=normalize(JSON.parse(await file.text()));if(!confirm(`${next.length} Ideen importieren und die aktuelle Liste ersetzen?`))return;const wasBlocked=blocked;blocked=false;if(!persist(next))blocked=wasBlocked;}catch(err){alert('Import nicht möglich: '+err.message);}finally{e.target.value='';}};
render();
